// 背景：历史 types.ts 同时实现 v1 reader、默认值和弱别名，形成了双持久模型。
// 目的：只聚合 final-v0.3 模块，不在聚合层新增解析、迁移或兼容分支。
// 上下文：包根是否暴露这些名字由后续计划裁决；当前仅供仓库内部统一导入。
export * from './scalars.js';
export * from './change.js';
export * from './project.js';
export * from './run.js';
export * from './workset.js';
export {
  SCENARIO_IDS,
  changeArtifactDirectorySchema,
  changeArtifactPathSchema,
  frozenByteBlobSchema,
  gitObjectFormatSchema,
  gitObjectIdSchema,
  normalizedAbsoluteRealPathSchema,
  projectAliasSchema,
  repositoryCodePathSchema,
  runBindingSchema,
  runLifecycleOwnerRefSchema,
  strictJsonValueSchema,
  strictWorksetBranchSchema,
  strictWorksetSlugSchema,
  worksetIdSchema,
  worksetOperationIdSchema,
  worksetReentryIdSchema,
  type ChangeArtifactDirectory,
  type ChangeArtifactDirectoryConstructionInput,
  type ChangeArtifactPath,
  type ChangeArtifactPathConstructionInput,
  type FrozenByteBlob,
  type FrozenByteBlobConstructionInput,
  type GitObjectFormat,
  type NormalizedAbsoluteRealPath,
  type NormalizedAbsoluteRealPathConstructionInput,
  type ProjectAlias,
  type ProjectAliasConstructionInput,
  type RepositoryCodePath,
  type RepositoryCodePathConstructionInput,
  type RunBinding,
  type RunBindingConstructionInput,
  type RunLifecycleOwnerRef,
  type RunLifecycleOwnerRefConstructionInput,
  type StrictChangeSlug,
  type StrictJsonValue,
  type StrictWorksetBranch,
  type StrictWorksetBranchConstructionInput,
  type StrictWorksetSlug,
  type StrictWorksetSlugConstructionInput,
  type WorksetId,
  type WorksetIdConstructionInput,
  type WorksetOperationId,
  type WorksetOperationIdConstructionInput,
  type WorksetReentryId,
  type WorksetReentryIdConstructionInput,
} from './public.js';
