import type { ScenarioProfile } from '../domain/types.js';

export const SCENARIOS: readonly ScenarioProfile[] = [
  {
    id: 'read-only-query',
    label: 'Read-only code or business query',
    description: 'Answer where a field, rule, call path, or business flow lives without modifying the repository.',
    workMode: 'READ_ONLY_QUERY',
    stages: ['research'],
    optionalStages: ['learn'],
    requiredArtifacts: ['research.md'],
    gates: ['No source-code writes', 'Every load-bearing statement cites code or a formal artifact'],
    requiredEvidence: ['code-references'],
    signals: ['where is', 'which service', 'business flow', 'field usage', 'explain code'],
    risk: 'LOW',
  },
  {
    id: 'bug-fix',
    label: 'Bug fix',
    description: 'Reproduce a defect, identify the root cause, implement one focused fix, and add a regression guard.',
    workMode: 'BUG_FIX',
    stages: ['reproduce', 'diagnose', 'plan', 'work', 'verify', 'learn'],
    optionalStages: ['research', 'design', 'review'],
    requiredArtifacts: ['research.md', 'tasks.yaml'],
    gates: ['No fix before reproducible evidence or an instrumentation plan', 'Regression evidence required'],
    requiredEvidence: ['reproduction', 'regression-test', 'full-test-suite'],
    signals: ['bug', 'defect', 'exception', 'unexpected', 'failing test', 'regression'],
    risk: 'MEDIUM',
  },
  {
    id: 'production-incident',
    label: 'Production incident',
    description: 'Mitigate customer impact first, preserve evidence, find root cause, verify recovery, and require a postmortem.',
    workMode: 'INCIDENT',
    stages: ['mitigate', 'research', 'diagnose', 'work', 'verify', 'release', 'learn'],
    optionalStages: ['reconcile', 'review'],
    requiredArtifacts: ['research.md', 'tasks.yaml'],
    gates: ['Mitigation and diagnosis are recorded separately', 'Emergency changes require explicit release approval'],
    requiredEvidence: ['incident-timeline', 'recovery-check', 'production-health', 'postmortem'],
    signals: ['incident', 'production down', 'outage', 'sev', 'customer impact', 'emergency'],
    risk: 'CRITICAL',
  },
  {
    id: 'small-feature',
    label: 'Small, well-understood feature',
    description: 'Deliver a focused feature through lightweight specification, design, planning, implementation, and verification.',
    workMode: 'FEATURE',
    stages: ['spec', 'design', 'plan', 'work', 'verify', 'archive'],
    optionalStages: ['research', 'review', 'learn'],
    requiredArtifacts: ['spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Acceptance criteria are observable', 'Each task is independently verifiable'],
    requiredEvidence: ['build', 'tests'],
    signals: ['add endpoint', 'small feature', 'clear requirement', 'single module'],
    risk: 'LOW',
  },
  {
    id: 'domain-feature',
    label: 'Complex domain feature',
    description: 'Recover current behavior and domain meaning before specifying and implementing a business capability.',
    workMode: 'FEATURE',
    stages: ['research', 'model', 'spec', 'design', 'plan', 'work', 'review', 'verify', 'learn', 'archive'],
    optionalStages: ['frame', 'reconcile'],
    requiredArtifacts: ['research.md', 'domain.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Blocking domain questions are resolved', 'Domain ownership changes require approval'],
    requiredEvidence: ['domain-decisions', 'behavior-tests', 'integration-tests'],
    signals: ['business rule', 'domain model', 'lifecycle', 'authorization', 'order state', 'insurance rule'],
    risk: 'HIGH',
  },
  {
    id: 'cross-service-change',
    label: 'Cross-service change',
    description: 'Coordinate contracts, ownership, rollout, compatibility, and verification across multiple services.',
    workMode: 'ARCHITECTURE_CHANGE',
    stages: ['research', 'model', 'spec', 'design', 'plan', 'work', 'review', 'verify', 'release', 'learn', 'archive'],
    optionalStages: ['map', 'reconcile', 'canary'],
    requiredArtifacts: ['research.md', 'domain.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Consumer impact is known', 'Contracts are versioned or backward compatible', 'Rollout order is explicit'],
    requiredEvidence: ['contract-tests', 'integration-tests', 'consumer-impact', 'runtime-health'],
    signals: ['multiple services', 'cross service', 'API consumer', 'event schema', 'distributed transaction'],
    risk: 'HIGH',
  },
  {
    id: 'migration-program',
    label: 'Long-running migration program',
    description: 'Map a destination through decision frontiers, execute multiple bounded changes, and retire old paths safely.',
    workMode: 'MIGRATION',
    stages: ['frame', 'map', 'research', 'model', 'spec', 'design', 'plan', 'work', 'verify', 'release', 'learn', 'archive'],
    optionalStages: ['reconcile', 'canary', 'review'],
    requiredArtifacts: ['intent.md', 'research.md', 'domain.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Destination and out-of-scope are explicit', 'Unknowns are represented as fog, not fake tasks', 'Retirement criteria exist'],
    requiredEvidence: ['dependency-map', 'compatibility-checks', 'migration-reconciliation', 'retirement-proof'],
    signals: ['migration', 'decommission', 'sunset', 'split monolith', 'move capability', 'multi-month'],
    risk: 'CRITICAL',
  },
  {
    id: 'architecture-evolution',
    label: 'Architecture evolution',
    description: 'Research current seams, model boundaries, challenge the proposed architecture, and evolve through reversible increments.',
    workMode: 'ARCHITECTURE_CHANGE',
    stages: ['research', 'model', 'design', 'review', 'plan', 'work', 'verify', 'learn', 'archive'],
    optionalStages: ['spec', 'map', 'reconcile'],
    requiredArtifacts: ['research.md', 'domain.md', 'design.md', 'tasks.yaml'],
    gates: ['Alternatives and trade-offs are documented', 'Non-trivial claims receive adversarial review'],
    requiredEvidence: ['architecture-review', 'characterization-tests', 'performance-or-operability-check'],
    signals: ['refactor architecture', 'module boundaries', 'DDD', 'decouple', 'replace framework'],
    risk: 'HIGH',
  },
  {
    id: 'performance-investigation',
    label: 'Performance investigation',
    description: 'Establish a measurable baseline, instrument boundaries, test one hypothesis at a time, and prove the improvement.',
    workMode: 'PERFORMANCE',
    stages: ['research', 'diagnose', 'design', 'plan', 'work', 'verify', 'learn'],
    optionalStages: ['reconcile', 'review', 'release'],
    requiredArtifacts: ['research.md', 'design.md', 'tasks.yaml'],
    gates: ['No optimization without a baseline', 'One hypothesis per experiment', 'Correctness must remain intact'],
    requiredEvidence: ['baseline-benchmark', 'profile-or-trace', 'after-benchmark', 'regression-tests'],
    signals: ['slow', 'latency', 'throughput', 'timeout', 'CPU', 'memory', 'performance regression'],
    risk: 'HIGH',
  },
  {
    id: 'security-change',
    label: 'Security-sensitive change',
    description: 'Model threats and trust boundaries, minimize privilege, implement defensively, and independently verify controls.',
    workMode: 'SECURITY',
    stages: ['research', 'model', 'spec', 'design', 'review', 'plan', 'work', 'verify', 'learn', 'archive'],
    optionalStages: ['reconcile', 'release'],
    requiredArtifacts: ['research.md', 'domain.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Threat model is explicit', 'Privilege and data exposure changes require approval', 'Reviewer context is independent'],
    requiredEvidence: ['security-tests', 'threat-review', 'dependency-or-secret-scan'],
    signals: ['authentication', 'authorization', 'permission', 'secret', 'PII', 'security', 'encryption'],
    risk: 'CRITICAL',
  },
  {
    id: 'data-migration',
    label: 'Data migration',
    description: 'Design expand-migrate-contract phases, checkpoints, reconciliation, rollback or forward-fix, and retirement.',
    workMode: 'MIGRATION',
    stages: ['research', 'model', 'spec', 'design', 'review', 'plan', 'work', 'verify', 'release', 'learn', 'archive'],
    optionalStages: ['map', 'reconcile', 'canary'],
    requiredArtifacts: ['research.md', 'domain.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Compatibility window is explicit', 'Checkpoint and compensation strategy exist', 'Irreversible operations require approval'],
    requiredEvidence: ['migration-dry-run', 'row-count-or-domain-reconciliation', 'rollback-or-forward-fix-test', 'post-migration-health'],
    signals: ['schema migration', 'backfill', 'data move', 'dual write', 'database migration'],
    risk: 'CRITICAL',
  },
  {
    id: 'frontend-feature',
    label: 'Frontend or UX feature',
    description: 'Align user intent and interaction design, implement accessible slices, and verify in a real browser.',
    workMode: 'FEATURE',
    stages: ['frame', 'spec', 'design', 'plan', 'work', 'qa', 'verify', 'learn', 'archive'],
    optionalStages: ['research', 'review', 'release', 'canary'],
    requiredArtifacts: ['intent.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Interaction states are defined', 'Accessibility expectations are explicit', 'Browser evidence is required'],
    requiredEvidence: ['component-tests', 'browser-qa', 'accessibility-check'],
    signals: ['UI', 'UX', 'page', 'component', 'frontend', 'React', 'browser'],
    risk: 'MEDIUM',
  },
  {
    id: 'new-product',
    label: 'New product or product direction',
    description: 'Challenge demand, identify the narrowest wedge, define success, then move into product and engineering design.',
    workMode: 'PRODUCT_DISCOVERY',
    stages: ['frame', 'research', 'spec', 'design', 'plan', 'work', 'qa', 'verify', 'release', 'canary', 'learn'],
    optionalStages: ['model', 'review', 'reconcile'],
    requiredArtifacts: ['intent.md', 'research.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Target user and status quo are concrete', 'Narrowest valuable wedge is explicit', 'Success signal is measurable'],
    requiredEvidence: ['user-or-market-evidence', 'product-acceptance', 'browser-qa', 'runtime-signal'],
    signals: ['new product', 'startup', 'MVP', 'is this worth building', 'product idea'],
    risk: 'HIGH',
  },
  {
    id: 'sdk-library',
    label: 'Shared SDK or library',
    description: 'Design public interfaces first, preserve compatibility, verify consumers, and publish a traceable artifact.',
    workMode: 'FEATURE',
    stages: ['research', 'spec', 'design', 'review', 'plan', 'work', 'verify', 'release', 'learn', 'archive'],
    optionalStages: ['model', 'reconcile'],
    requiredArtifacts: ['research.md', 'spec.md', 'design.md', 'tasks.yaml'],
    gates: ['Public API is explicit', 'Compatibility policy is defined', 'Consumer impact is verified'],
    requiredEvidence: ['API-compatibility', 'consumer-tests', 'package-build'],
    signals: ['SDK', 'library', 'package', 'public API', 'shared module'],
    risk: 'HIGH',
  },
  {
    id: 'emergency-hotfix',
    label: 'Emergency hotfix',
    description: 'Use a reduced but explicit gate: reproduce, make the smallest reversible change, verify, release, and perform mandatory follow-up.',
    workMode: 'INCIDENT',
    stages: ['reproduce', 'diagnose', 'work', 'verify', 'release', 'learn'],
    optionalStages: ['research', 'review', 'reconcile'],
    requiredArtifacts: ['research.md', 'tasks.yaml'],
    gates: ['Scope is minimal', 'Waived checks are recorded', 'Post-release follow-up is mandatory'],
    requiredEvidence: ['reproduction', 'focused-regression', 'smoke-test', 'production-health'],
    signals: ['hotfix', 'urgent fix', 'emergency patch', 'production bug now'],
    risk: 'CRITICAL',
  },
  {
    id: 'release-failure',
    label: 'Release or deployment failure',
    description: 'Pause promotion, inspect delivery evidence, choose rollback or forward-fix, and verify environment health.',
    workMode: 'RELEASE',
    stages: ['mitigate', 'research', 'diagnose', 'reconcile', 'work', 'verify', 'release', 'learn'],
    optionalStages: ['review'],
    requiredArtifacts: ['research.md', 'tasks.yaml'],
    gates: ['Promotion is paused before investigation', 'Rollback capability is checked instead of assumed'],
    requiredEvidence: ['deployment-logs', 'rollback-or-forward-fix-result', 'environment-health'],
    signals: ['deployment failed', 'release failed', 'rollback', 'canary failed', 'CI/CD'],
    risk: 'CRITICAL',
  },
];

const scenarioMap = new Map(SCENARIOS.map((scenario) => [scenario.id, scenario]));

export function getScenario(id: string): ScenarioProfile {
  const scenario = scenarioMap.get(id);
  if (!scenario) {
    throw new Error(`Unknown scenario '${id}'. Run 'omnai scenario list' to see available profiles.`);
  }
  return scenario;
}

export function detectScenario(input: string): ScenarioProfile {
  const normalized = input.toLowerCase();
  const scored = SCENARIOS.map((scenario) => ({
    scenario,
    score: scenario.signals.reduce(
      (total, signal) => total + (normalized.includes(signal.toLowerCase()) ? signal.length : 0),
      0,
    ),
  })).sort((left, right) => right.score - left.score);

  const best = scored[0];
  return best && best.score > 0 ? best.scenario : getScenario('small-feature');
}

export function listScenarios(): readonly ScenarioProfile[] {
  return SCENARIOS;
}
