import type { ScenarioProfile } from '../domain/types.js';

export function intentTemplate(title: string, scenario: ScenarioProfile): string {
  return `# Intent: ${title}\n\n## Goal\n\nDescribe the outcome this change must create.\n\n## Problem\n\nDescribe the user, business, or engineering problem without assuming a solution.\n\n## Scenario\n\n- Profile: \`${scenario.id}\`\n- Work mode: \`${scenario.workMode}\`\n- Default risk: \`${scenario.risk}\`\n\n## Success Signals\n\n- A measurable signal that proves the outcome.\n\n## Scope\n\n- In scope: the smallest valuable result.\n\n## Non-goals\n\n- Explicitly excluded work.\n`;
}

export const researchTemplate = `# Current-State Report\n\n## Research Question\n\n## Scope\n\n## Executive Summary\n\n## Current Behavior\n\n## Entry Points\n\n## Data Flow\n\n## Dependencies\n\n## Persistence and External Systems\n\n## Similar Patterns\n\n## Architecture Lens\n\n### Current Topology, Ownership, and Callers\n\n### Dependency Direction, Interfaces, Seams, and Adapters\n\n### Constraints, Risks, Leakage, and Locality\n\n### Architecture Evidence\n\n## Historical Lineage\n\n### Previous Approaches\n\n### Why They Changed\n\n### Constraints That Still Apply\n\n### Constraints That No Longer Apply\n\n## Confirmed Facts\n\n## Unconfirmed Assumptions\n\n## Open Questions\n\n## Evidence References\n`;

export const domainTemplate = `# Domain Model\n\n## Context\n\n## Ubiquitous Language\n\n| Term | Canonical meaning | Not this | Evidence |\n| --- | --- | --- | --- |\n\n## Actors and Subjects\n\n## Entities and Value Objects\n\n## Lifecycles and State Transitions\n\n## Ownership and Boundaries\n\n## Invariants\n\n## Edge-Case Scenarios\n\n## Resolved Decisions\n\n## Open Decisions\n\n## ADR Candidates\n`;

export const specTemplate = `# Change Specification\n\n## Why\n\n## Added Requirements\n\n## Modified Requirements\n\n## Removed Requirements\n\n## Preserved Constraints\n\n## Architectural Impact and Constraints\n\n### Affected Callers and Boundaries\n\n### Preserved Invariants and Compatibility\n\n### Decisions Deferred to Design\n\n## Acceptance Criteria\n\nUse stable IDs such as \`AC-001\` and state observable outcomes.\n\n## Non-goals\n\n## Compatibility and Migration Expectations\n\n## Open Questions\n`;

export const contractTemplate = `# Boundary Contract\n\n## Contract Type\n\nHTTP API, event, public library API, or another producer/consumer boundary.\n\n## Current Contract\n\n## Target Contract\n\n## Field Semantics\n\n| Field | Type | Nullable | Default | Meaning |\n| --- | --- | --- | --- | --- |\n\n## Error Semantics\n\n## Producers\n\n## Consumers\n\n## Compatibility\n\n## Migration Strategy\n\n## Contract Evidence\n`;

export const designTemplate = `# Technical Design\n\n## Design Goals\n\n## Constraints\n\n## Current Architecture\n\n## Architecture Applicability\n\nApplicability: \`not-applicable\` | \`focused\` | \`full\`\n\nReason:\n\nFor \`not-applicable\`, provide only the short applicability rationale above; do not complete the focused/full assessment or invent \`MOD-*\`, \`IF-*\`, \`SEAM-*\`, or \`ADP-*\` IDs.\n\n## Module-Boundary Assessment (\`focused\`/\`full\` only)\n\n### Modules and Responsibilities (\`focused\`/\`full\` only)\n\n| Module ID | Responsibility | Owner | Callers | Owned data | Hidden complexity | Locality |\n| --- | --- | --- | --- | --- | --- | --- |\n| MOD-001 (focused/full example only) | | | | | | |\n\n### Interface Semantics (\`focused\`/\`full\` only)\n\n| Interface ID | Module ID | Operations and semantics | Invariants | Ordering, lifecycle, and errors | Configuration, cancellation, retries, and performance | External contract ID |\n| --- | --- | --- | --- | --- | --- | --- |\n| IF-001 (focused/full example only) | | | | | | |\n\n### Seams, Adapters, and Dependency Direction (\`focused\`/\`full\` only)\n\n| Seam ID | Adapter ID | From module | Dependency and direction | Category | Actual variation | Migration and retirement |\n| --- | --- | --- | --- | --- | --- | --- |\n| SEAM-001 (focused/full example only) | ADP-001 | | | | | |\n\n### Depth, Leverage, Locality, and Deletion Test (\`focused\`/\`full\` only)\n\n- Depth:\n- Leverage:\n- Locality:\n- Deletion test:\n\n### Boundary Enforcement and Interface Test Surface (\`focused\`/\`full\` only)\n\n| Interface ID | Dependency/package/export rules | Characterization evidence | Contract evidence | Integration evidence | Operability evidence |\n| --- | --- | --- | --- | --- | --- |\n| IF-001 (focused/full example only) | | | | | |\n\n## Considered Approaches\n\n### Recommended Approach\n\n### Alternatives and Trade-offs\n\n## Components and Responsibilities\n\n## Interfaces and Contracts\n\n## Data Flow\n\n## State and Persistence\n\n## Error Handling and Recovery\n\n## Security and Privacy\n\n## Observability\n\n## Testing Strategy\n\n## Deployment, Migration, and Rollback\n\n## Risks and Mitigations\n\n## Approval\n`;

export const issueTemplate = `# Issue Analysis\n\n## Triage\n\n## Expected vs Actual\n\n## Reproduction\n\n## Evidence\n\n## Boundary Trace\n\n## Hypotheses\n\n## Confirmed Root Cause\n\n## Fix Strategy\n\n## Regression Plan\n`;

export const fixTemplate = `# Fix Strategy\n\n## Root Cause Addressed\n\n## Chosen Fix\n\n## Alternatives Rejected\n\n## Scope\n\n## Regression Guard\n\n## Rollback / Recovery\n`;

export const deliveryTemplate = `# Delivery Readiness\n\n## Artifact Identity\n\n## Required Gates\n\n## Rollout Strategy\n\n## Rollback / Forward-Fix Strategy\n\n## Activation\n\n## Post-release Signals\n\n## Human Approval\n`;

export const emptyTaskFile = `schemaVersion: 1\nrevision: REV-0001\ngeneratedFrom: []\ntasks: []\n`;

export const projectGlossaryTemplate = `# Project Glossary\n\nOnly stable, reviewed domain language belongs here. Change-local discoveries stay in each change's \`domain.md\` until promoted.\n\n| Term | Canonical meaning | Scope | Source |\n| --- | --- | --- | --- |\n`;

export const projectPoliciesTemplate = `# OmnAI Project Policies\n\n## Rules, Skills, Guards\n\n- Rules define what MUST remain true.\n- Skills describe how an agent should perform work.\n- Guards enforce hard transitions independently of the host.\n\n## Evidence\n\n- Any behavior change MUST have fresh verification evidence before completion.\n- Public API or event changes MUST include compatibility evidence.\n- Data migrations MUST include reconciliation and rollback or forward-fix guidance.\n- P0/P1 work MUST have an explicit recovery path and human approval before ship.\n\n## Scope\n\n- Agents MUST NOT make unrelated cleanup changes while implementing a task.\n- High-risk, irreversible, or cross-service decisions require explicit human approval.\n\n## Knowledge\n\n- Runtime memory is not a source of truth.\n- Knowledge is promoted only after the originating change is verified.\n`;

export const learningsIndexTemplate = `# Validated Learnings\n\nThis index links durable, evidence-backed learnings promoted from completed changes.\n`;
